### PR TITLE
fix: dataindex为数组时排序错误，数组列排到最后

### PR DESCRIPTION
**Pull request by wangruiStart**
### `General`

> ✏️ Mark the necessary items without changing the structure of the PR template.

- [ ] Pull request template structure not broken

### `Type`

> ℹ️ What types of changes does your code introduce?

> 👉 _Put an `x` in the boxes that apply_

- [x ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### `Checklist`

> ℹ️ Check all checkboxes - this will indicate that you have done everything in accordance with the rules in [CONTRIBUTING](contributing.md).

> 👉 _Put an `x` in the boxes that apply._

- [ x] My code follows the style guidelines of this project
- [x ] Is the code format correct
- [ x] Is the git submission information standard?
- [x ] My code follows the style guidelines of this project
- [x ] I have performed a self-review of my own code
- [x ] I have commented my code, particularly in hard-to-understand areas
- [ x] I have made corresponding changes to the documentation
- [ x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x ] New and existing unit tests pass locally with my changes
- [ x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by evanlee01 — APPROVED** [review]

**Comment by likui628** [comment]
没明白此PR解决了什么问题，能不能说明下

**Comment by wangruiStart** [comment]
> 没明白此PR解决了什么问题，能不能说明下

当table的dataIndex是数组时，之前的逻辑会判断 title,但是判断逻辑写的有问题，应该是typeof title.导致最后的columnOptions的value是空字符串。进而导致tableColumnsUpdate方法中`const colIdx = columns.findIndex((o) => o.key === opt.value);`colIdx找不到，所有dataindex为数组的列都会被插到最后，改变了原有配置的columns的顺序

**Comment by Allure-eve** [comment]
这个代码错误好低级，在我使用这样的dataIndex的时候 排序功能就失效
```JavaScript
   {
      title: '歌手',
      dataIndex: ['artist', 'name'],
      width: 200,
    },
```

经过我的排查 发现 src/components/Table/src/components/settings/ColumnSetting.vue:547行以及上面的542行的label 都有该错误 

错误非常低级

```JavaScript
options.push({
          label:
            typeof col.title === 'string'
              ? col.title
              : col.customTitle === 'string' // ？？？？ 只有当col.customTitle 的值为string的时候才去使用col.customTitle 吗 typeof呢 我请问
                ? col.customTitle
                : '',
          value:
            typeof col.dataIndex === 'string'
              ? col.dataIndex
              : col.title === 'string' // ？？？？ 只有当col.title的值为string的时候才去使用col.title吗 typeof呢 我请问
                ? col.title
                : '',
          column: {
            defaultHidden: col.defaultHidden,
          },
          fixed: col.fixed,
        });
```

**Comment by wangruiStart** [comment]
> I think we can close this PR? The was solved in [64a4992](https://github.com/vbenjs/vue-vben-admin/commit/64a4992a84dadb33614e937f5d7464dcd312a1bd)
This error pertains to the fix in the Ant Design Vue Table component, not the Vxe-Table component.

**Comment by wangruiStart** [comment]
> I think we can close this PR? The was solved in [64a4992](https://github.com/vbenjs/vue-vben-admin/commit/64a4992a84dadb33614e937f5d7464dcd312a1bd)

This error pertains to the fix in the Ant Design Vue Table component, not the Vxe-Table component.

**Pull request closed without merging**
