### PR TITLE
表单设置初始值defaultValue时候使用深度拷贝

### PR DESCRIPTION
**Pull request by iconFehu**
### `General`

> ✏️ Mark the necessary items without changing the structure of the PR template.

- [x] Pull request template structure not broken

### `Type`

> ℹ️ What types of changes does your code introduce?

> 👉 _Put an `x` in the boxes that apply_

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### `Checklist`

> ℹ️ Check all checkboxes - this will indicate that you have done everything in accordance with the rules in [CONTRIBUTING](contributing.md).

> 👉 _Put an `x` in the boxes that apply._

- [x] My code follows the style guidelines of this project
- [x] Is the code format correct
- [x] Is the git submission information standard?
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by iconFehu** [comment]
1.表单设置初始值defaultValue时候使用深度拷贝
2.优化BasicTree组件
3.解决Demo中懒加载异步树加载失败

**Comment by zhang-jianxun** [comment]
会导致 #2078 的问题

**Comment by zuihou** [comment]
> 1.表单设置初始值defaultValue时候使用深度拷贝 2.优化BasicTree组件 3.解决Demo中懒加载异步树加载失败 4.tree树形异步懒加载,点击两次才能关闭

image

image


BasicForm.vue 中的以下代码，会导致点击”查询“时， ApiSelect、ApiRadioGroup 等组件触发2次
```
   if (unref(getProps).showAdvancedButton) {
          return cloneDeep(
            schemas.filter((schema) => schema.component !== 'Divider') as FormSchema[],
          );
        } else {
          return cloneDeep(schemas as FormSchema[]);
        }
```

**Comment by zuihou** [comment]
image

注释 cloneDeep 后，恢复正常

**Comment by zuihou** [comment]
@jinmao88  @iconFehu

**Pull request merged**
