### PR TITLE
chore: update `unplugin-config`

### PR DESCRIPTION
**Pull request by kirklin**
### `General`

> ✏️ Mark the necessary items without changing the structure of the PR template.

- [ ] Pull request template structure not broken

### `Type`

> ℹ️ What types of changes does your code introduce?

> 👉 _Put an `x` in the boxes that apply_

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### `Checklist`

> ℹ️ Check all checkboxes - this will indicate that you have done everything in accordance with the rules in [CONTRIBUTING](contributing.md).

> 👉 _Put an `x` in the boxes that apply._

- [ ] My code follows the style guidelines of this project
- [ ] Is the code format correct
- [ ] Is the git submission information standard?
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by wangjue666** [comment]
@kirklin 哥你这个包升级了啥 能简要说说吗

**Comment by kirklin** [comment]
最大的变化是API设计，也就是Options重构了，暂时不能无缝升级，所以交了个pr，后续应该不太会有这种大重构了。然后多增加了自定义脚本注入位置，以及支持指定环境变量的位置

**Comment by wangjue666** [comment]
@kirklin  
image 打完包后并没有直接填充进去

**Comment by wangjue666** [comment]
image
之前打完包会直接填充

**Comment by wangjue666** [comment]
你打开网站也能直观感受到 他会等那个mainjs加载完才会显示出正确的title

**Comment by kirklin** [comment]
image

**Comment by wangjue666** [comment]
image

**Comment by wangjue666** [comment]
我先回滚下吧， 修好再提个pr好了

**Comment by kirklin** [comment]
我大概懂了，`vite-plugin-html`没办法识别转义后的符号，
原本
```html
<%= VITE_GLOB_APP_TITLE %>
```
会变成
```
&lt;%= VITE_GLOB_APP_TITLE %&gt;
```

**Pull request merged**
