### PR TITLE
fix: 裁剪上传接口与uploadModal统一：url

### PR DESCRIPTION
**Pull request by yuhldr**
### `General`

> ✏️ Mark the necessary items without changing the structure of the PR template.

- [x] Pull request template structure not broken

### `Type`

> ℹ️ What types of changes does your code introduce?

> 👉 _Put an `x` in the boxes that apply_

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### `Checklist`

> ℹ️ Check all checkboxes - this will indicate that you have done everything in accordance with the rules in [CONTRIBUTING](contributing.md).

> 👉 _Put an `x` in the boxes that apply._

- [x] My code follows the style guidelines of this project
- [x] Is the code format correct
- [x] Is the git submission information standard?
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by yuhldr** [comment]
上传组件接口是 `url`，如下，所以建议裁剪组件上传接口统一。
https://github.com/vbenjs/vue-vben-admin/blob/31042de6bc0683132f57262e452dc3aa15cc8de0/src/components/Upload/src/UploadModal.vue#L254

**Comment by billyshen26** [comment]
emit('uploadSuccess', { source: previewSource.value, data: result.url });
应该改成 
emit('uploadSuccess', { source: previewSource.value, data: result.data.url });
才能拿到数据吧。（感受是改出了bug）

当然这也要去后端返回结构里的一级结构就有url这个字段， 感觉不如之前的result.data来的灵活
vue-vben-admin/src/components/Upload/src/UploadModal.vue
里面应该改成
fileList.push(responseData);   比较灵活

**Comment by yuhldr** [comment]
确实应该是 `result.data.url`，我这么写是因为我自己的内容里，上传接口这里也改了，我给忘了 https://github.com/vbenjs/vue-vben-admin/blob/d3ec7a58ad96eda0db23a99614b65fa59602ec10/src/utils/http/axios/Axios.ts#L147-L157 
不改的话，没有校验token，谁都能上传，容易被人利用
```ts
    return this.post({
      ...config,
      timeout: 10 * 60 * 1000,
      method: 'POST',
      data: formData,
      headers: {
        'Content-type': ContentTypeEnum.FORM_DATA,
        // @ts-ignore
        ignoreCancelToken: true,
      },
    });
```

**Comment by yuhldr** [comment]
@billyshen26 另外我个人认为， `fileList.push(responseData); 比较灵活`这个不合适，因为接口要有统一的 result 管理，用以区分各种报错，这个项目的其它接口也是这么做的，这也是为什么我把上传的接口也改成统一的 `this.post` （这个我忘了提交到这个项目了）

**Pull request merged**
