### PR TITLE
refactor: use `unplugin-config`

### PR DESCRIPTION
**Pull request by kirklin**
### `General`

> ✏️ Mark the necessary items without changing the structure of the PR template.

- [x] Pull request template structure not broken

### `Type`

> ℹ️ What types of changes does your code introduce?

> 👉 _Put an `x` in the boxes that apply_

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### `Checklist`

> ℹ️ Check all checkboxes - this will indicate that you have done everything in accordance with the rules in [CONTRIBUTING](contributing.md).

> 👉 _Put an `x` in the boxes that apply._

- [ ] My code follows the style guidelines of this project
- [ ] Is the code format correct
- [ ] Is the git submission information standard?
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by likui628** [comment]
@jinmao88

**Comment by wangjue666** [comment]
@kirklin  打包完后空格消失了 
image

如果把 `VITE_GLOB_APP_TITLE = Vben Admin2` 标题显示正常了，但又出现
image

**Comment by kirklin** [comment]
> @kirklin 打包完后空格消失了 image
> 
> 如果把 `VITE_GLOB_APP_TITLE = Vben Admin2` 标题显示正常了，但又出现 image

应该是规则不一样的原因，我会自动把空格删除掉。

**Comment by wangjue666** [comment]
@kirklin  如果把 **VITE_GLOB_APP_TITLE = Vben Admin2** 这个问题还是会出现 `Uncaught TypeError: Cannot destructure property 'VITE_GLOB_APP_TITLE' of 'C' as it is undefined` 之前vben 是有不少人提过这样问题

**Comment by wangjue666** [comment]
@kirklin  我先将这块回滚了， 修复好你再提个PR吧 :)

**Pull request merged**
