### PR TITLE
fix: 修复#2030改动引起的可展开table失效

### PR DESCRIPTION
**Pull request by GauharChan**
[#2030 ](https://github.com/vbenjs/vue-vben-admin/pull/2030)改动后，ExpandTable demo页面达不到预期了。

此pr修改前
image
此pr修改后
image

控制台也没有slot的警告，因为这个不属于column.slots

### `General`

> ✏️ Mark the necessary items without changing the structure of the PR template.

- [ ] Pull request template structure not broken

### `Type`

> ℹ️ What types of changes does your code introduce?

> 👉 _Put an `x` in the boxes that apply_

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### `Checklist`

> ℹ️ Check all checkboxes - this will indicate that you have done everything in accordance with the rules in [CONTRIBUTING](contributing.md).

> 👉 _Put an `x` in the boxes that apply._

- [x] My code follows the style guidelines of this project
- [x] Is the code format correct
- [x] Is the git submission information standard?
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by qyn980427** [comment]
横向滚动会失效

**Comment by GauharChan** [comment]
> 横向滚动会失效

我再次看了demo，没有发现问题，并且这个demo中没有设置table的滚动

**Comment by WitMiao** [comment]
> > 横向滚动会失效
> 
> 我再次看了demo，没有发现问题，并且这个demo中没有设置table的滚动

image
image

我试了一下小屏幕是会出现这个问题，列被收缩进去，但不能滚动看到，两侧的fixed也失效了
应该是expandedRowRender实现的问题

**Comment by GauharChan** [comment]
> > > 横向滚动会失效
> > 
> > 
> > 我再次看了demo，没有发现问题，并且这个demo中没有设置table的滚动
> 
> image image
> 
> 我试了一下小屏幕是会出现这个问题，列被收缩进去，但不能滚动看到，两侧的fixed也失效了 应该是expandedRowRender实现的问题

如果你确定是expandedRowRender的问题的话，那就去到ant-design-vue的层面吗，这个demo只是用antdv组件的expandedRowRender插槽而已

**Comment by qyn980427** [comment]
#2050  看看这个试试

**Comment by GauharChan** [comment]
> #2050 看看这个试试

害，你这倒是提醒我了，这个demo本来就有提示不能和scroll共用；所以你说的滚动问题和我所提pr的没有关系。我觉得提个issue讨论更加合适。
然后你这个pr只是单存的把propsData中剔除scroll这句代码注释，有没有考虑过作者写的时候为什么要加上这个限制呢

**Pull request merged**
