### PR TITLE
fix: 修复ApiRadioGroup第一次change选值后依然触发必输校验

### PR DESCRIPTION
**Pull request by a63149300**
ApiRadioGroup没有设置defaultValue，设置了required: true，在第一次change选值后，由于set设置了nextTick，先触发了组件change但没有拿到第一次设置的值，导致表单当无值校验处理。

### `General`

> ✏️ Mark the necessary items without changing the structure of the PR template.

- [ ] Pull request template structure not broken

### `Type`

> ℹ️ What types of changes does your code introduce?

> 👉 _Put an `x` in the boxes that apply_

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### `Checklist`

> ℹ️ Check all checkboxes - this will indicate that you have done everything in accordance with the rules in [CONTRIBUTING](contributing.md).

> 👉 _Put an `x` in the boxes that apply._

- [ ] My code follows the style guidelines of this project
- [ ] Is the code format correct
- [ ] Is the git submission information standard?
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by CyrusZhou-CN** [comment]
会导致ApiSelect  onChange: (e: any, options: any) => 无法获得 options 的值

**Review by mmdjiji — APPROVED** [review]
感谢，我也遇到了这个问题，用此方法解决了，希望早日merge

**Comment by PigTom-c** [comment]
> 感谢，我也遇到了这个问题，用此方法解决了，希望早日merge

就是不知道为什么去掉了就可以了

**Comment by mmdjiji** [comment]
> > 感谢，我也遇到了这个问题，用此方法解决了，希望早日merge
> 
> 就是不知道为什么去掉了就可以了

我只是不是很理解为什么作者放到 `nextTick` 的回调里，因为这个是下一次触发，必然导致这样的结果

**Comment by PigTom-c** [comment]
> > > 感谢，我也遇到了这个问题，用此方法解决了，希望早日merge
> > 
> > 
> > 就是不知道为什么去掉了就可以了
> 
> 我只是不是很理解为什么作者放到 `nextTick` 的回调里，因为这个是下一次触发，必然导致这样的结果

怀疑是ant版本的问题  之前用ant2的版本没有出现过这个问题

**Pull request closed without merging**
