### PR TITLE
fix(BasicForm): 修复表单项通过ifShow控制隐藏后其表单值还存在

### PR DESCRIPTION
**Pull request by zwtvip**
### `General`

> ✏️ Mark the necessary items without changing the structure of the PR template.

- [ ] Pull request template structure not broken

### `Type`

> ℹ️ What types of changes does your code introduce?

> 👉 _Put an `x` in the boxes that apply_

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### `Checklist`

> ℹ️ Check all checkboxes - this will indicate that you have done everything in accordance with the rules in [CONTRIBUTING](contributing.md).

> 👉 _Put an `x` in the boxes that apply._

- [ ] My code follows the style guidelines of this project
- [ ] Is the code format correct
- [ ] Is the git submission information standard?
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by wangjue666** [comment]
这个存疑不算bug, 至少在我这边业务场景下， ifshow隐藏后，还需要传值的必要， 先开个issue讨论下吧，记得有类似的issue

**Comment by zwtvip** [comment]
> 这个存疑不算bug, 至少在我这边业务场景下， ifshow隐藏后，还需要传值的必要， 先开个issue讨论下吧，记得有类似的issue

@wangjue666 想要隐藏后传值可以用show,ifshow代表不渲染表单项，我的理解是不应该出现这个field

**Comment by wangjue666** [comment]
ifshow和show场景 我的用法是在一些自定义组件上，渲染吃力就用ifshow, 可以提个issue再探讨下这个问题~

**Comment by wangjue666** [comment]
在formconfig配置项做成一个是否启用的开关，是比较合适的情形，这样对业务侵入性小

**Pull request closed without merging**
