### PR TITLE
fix(ATypographyParagraph): type:check error

### PR DESCRIPTION
**Pull request by jiaowoxiaobala**
### `General`

> ✏️ Mark the necessary items without changing the structure of the PR template.

- [ ] Pull request template structure not broken

### `Type`

> ℹ️ What types of changes does your code introduce?

> 👉 _Put an `x` in the boxes that apply_

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### `Checklist`

> ℹ️ Check all checkboxes - this will indicate that you have done everything in accordance with the rules in [CONTRIBUTING](contributing.md).

> 👉 _Put an `x` in the boxes that apply._

- [x] My code follows the style guidelines of this project
- [x] Is the code format correct
- [x] Is the git submission information standard?
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by wangjue666** [comment]
@jiaowoxiaobala  我昨天也看到这个类型问题了, `Typography`这个组件的`props`倒是有 `style`的定义, `Typography.Paragraph`就没有

**Comment by jiaowoxiaobala** [comment]
> @jiaowoxiaobala 我昨天也看到这个类型问题了, `Typography`这个组件的`props`倒是有 `style`的定义, `Typography.Paragraph`就没有

对

**Comment by wangjue666** [comment]
@jiaowoxiaobala 你有兴趣加入vben吗？最近我们正在着手开发vben3项目，同时也在寻找志愿者来帮助维护vben2。如果你有兴趣的话非常欢迎你的加入！

**Comment by jiaowoxiaobala** [comment]
> @jiaowoxiaobala 你有兴趣加入vben吗？最近我们正在着手开发vben3项目，同时也在寻找志愿者来帮助维护vben2。如果你有兴趣的话非常欢迎你的加入！
有兴趣，不过时间上可能不是那么充裕

**Comment by jiaowoxiaobala** [comment]
> @jiaowoxiaobala 你有兴趣加入vben吗？最近我们正在着手开发vben3项目，同时也在寻找志愿者来帮助维护vben2。如果你有兴趣的话非常欢迎你的加入！

@wangjue666  有兴趣的，不过时间上可能不是那么充裕

**Comment by wangjue666** [comment]
@jiaowoxiaobala  好 也提供下你的qq吧，拉你进组织群

**Comment by jiaowoxiaobala** [comment]
> @jiaowoxiaobala 好 也提供下你的qq吧，拉你进组织群

 ok，415313629

**Comment by wangjue666** [comment]
@jiaowoxiaobala   嗯嗯，你加下金毛的QQ `63992745`， 他来邀请你进

**Comment by jiaowoxiaobala** [comment]
> @jiaowoxiaobala 嗯嗯，你加下金毛的QQ `63992745`， 他来邀请你进

ok

**Pull request merged**
