### PR TITLE
fix(BasicForm): setFieldsValue not work in form when use date comp

### PR DESCRIPTION
**Pull request by electroluxcode**
### `General`

> ✏️ Mark the necessary items without changing the structure of the PR template.

- [x] Pull request template structure not broken

### `Type`

> ℹ️ What types of changes does your code introduce?

> 👉 _Put an `x` in the boxes that apply_

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

fix https://github.com/vbenjs/vue-vben-admin/issues/3818

### CODE REVIEW

**Comment by electroluxcode** [comment]
补一个用于测试的例子
```vue
<template>
  <Alert message="bug" />
  <BasicForm @register="registerCustom" class="my-5" />
  <Button @click="set">点我设置值</Button>
</template>

<script setup lang="ts">
  import { Alert, Button } from 'ant-design-vue';
  import { BasicForm, useForm } from '@/components/Form';
  import dayjs from 'dayjs';
  const [registerCustom, { getFieldsValue, setFieldsValue }] = useForm({
    baseColProps: { span: 24 },
    labelWidth: 124,
    schemas: [
      {
        field: '[startTime1, endTime1]',
        label: 'field1',
        component: 'RangePicker',
        componentProps: {
          placeholder: ['开始时间', '结束时间'],
          defaultValue: [dayjs('2024-12-01 11:11:11'), dayjs('2024-12-01 12:12:12')],
        },
      },{
        field: '[startTime2, endTime2]',
        label: '上架时间',
        
        component: 'TimeRangePicker',
        componentProps: {
          format: 'HH:mm:ss',
          placeholder: ['开始时间', '结束时间'],
          defaultValue: [dayjs('11:11:11',"HH:mm:ss"), dayjs('12:12:12',"HH:mm:ss")],
        },
      },
    ],
    showActionButtonGroup: true,
  });
  const set = () => {
    setFieldsValue({
      endTime1: '2028-12-01 12:12:12',
    });
    setFieldsValue({
      startTime2: dayjs('18:18:01',"HH:mm:ss"),
      endTime2: dayjs('19:19:01',"HH:mm:ss"),
    });
    console.log('getFieldsValue:', getFieldsValue());
  };
</script>


```

**Comment by acegank** [comment]
set的是HH:mm, get后变成了 YYYY-MM-DD HH:mm 了

**Comment by acegank** [comment]
在设置了valueFormat 还需要设置value的fomat，源码里只判断了是否有valueFormat，我的理解正常应该要根据valueFormat返回，否则valueFormat没啥意义，就只是个开关

**Comment by aTann** [comment]
在 `Adapt common component` 处理中，使用了 `constructValue = get(value, key);` 会导致当 `field` 使用一些基础类型构造函数原型链上相同的命名时候（例如：`link`），`setFieldsValue` 会出现返回一个函数的 bug

image
```
const record = {link: 'xxx'}

const formSchemas =  [{
      field: 'link',
      component: 'Input',
      label: '链接',
 }]
 ```

**Pull request merged**
