### PR TITLE
fix: watch open logic lost after build

### PR DESCRIPTION
**Pull request by xachary**
### `General`

> 使用 Drawer 的时候，在组件内部使用 getOpen 获取是否打开状态，发现 build 之后没有生效。对比build前后代码，关键逻辑丢失，如下：
S0Ip7PTpt9
> 不考虑 build 配置，微调判断可以避免这个问题。

- [x] Pull request template structure not broken

### `Type`

> ℹ️ What types of changes does your code introduce?

> 👉 _Put an `x` in the boxes that apply_

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### `Checklist`

> ℹ️ Check all checkboxes - this will indicate that you have done everything in accordance with the rules in [CONTRIBUTING](contributing.md).

> 👉 _Put an `x` in the boxes that apply._

- [x] My code follows the style guidelines of this project
- [x] Is the code format correct
- [x] Is the git submission information standard?
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by wangjue666** [comment]
惊呆了这是啥原理

**Comment by xachary** [comment]
image

**Comment by xachary** [comment]
> pnpm preview

打开 Drawer

image

**Comment by xachary** [comment]
image

貌似也可以解决，可能就是这样原因，&& 后面带了个 ?.()

**Comment by wangjue666** [comment]
> image
> 
> 貌似也可以解决，可能就是这样原因，&& 后面带了个 ?.()

这个中，改成这样 代码也好阅读

**Comment by wangjue666** [comment]
我猜测vite 是由于开发环境和打包环境代码编译工具不一样， 导致`Rollup`打包有问题， 或许要考虑升级vite版本了，现在最新版本已经是5.x了

**Comment by xachary** [comment]
@wangjue666 

> 我猜测vite 是由于开发环境和打包环境代码编译工具不一样， 导致`Rollup`打包有问题， 或许要考虑升级vite版本了，现在最新版本已经是5.x了

行，按上面代码改。

vite5，期待升级。

如无需在此时修改，可以close。

**Review by likui628 — APPROVED** [review]

**Review by wangjue666 — APPROVED** [review]

**Pull request merged**
