### PR TITLE
feat(MultipleTab): add tabs auto collapse interaction and setting

### PR DESCRIPTION
**Pull request by xachary**
### `General`

> 部分页面在开启“fold”模式下，希望达到“沉浸式”的全屏展示，同时不影响“tabs”的切换，且相比于“fullContent”模式需要点击2次才能切换，增加“fold”模式下“tabs”可以自动收起，可以1次点击即可切换。

- [x] Pull request template structure not broken

### `Type`

> ℹ️ What types of changes does your code introduce?

> 👉 _Put an `x` in the boxes that apply_

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### `Checklist`

> ℹ️ Check all checkboxes - this will indicate that you have done everything in accordance with the rules in [CONTRIBUTING](contributing.md).

> 👉 _Put an `x` in the boxes that apply._

- [x] My code follows the style guidelines of this project
- [x] Is the code format correct
- [x] Is the git submission information standard?
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by xachary** [comment]
我这边还有一个调整，上述的模式下，“fold”的时候"设置"按钮会移动到“tabs”栏上面（“刷新”按钮左边），先看看这个模式是否通过你们的评审。

**Comment by wangjue666** [comment]
@xachary 我开启了 自动收起标签页 标签切换好像没有变化, 能否详细描述下或者录制个视频 这个功能该如何使用吗？

**Comment by xachary** [comment]
@wangjue666 好的，请看：

https://github.com/vbenjs/vue-vben-admin/assets/16830398/a6ae928b-d5df-40d8-9dfd-89b64436eeb0

”fold“的时候才会生效获得”全屏“的体验

**Comment by wangjue666** [comment]
@xachary  可以，你可以重新fork下仓库，开个新分支进行pr，这样你之前提交的commit信息不会出现在新pr里面

image

每次pr前主动点下更新这样可以尽可能避免代码冲突

image




> 我这边还有一个调整，上述的模式下，“fold”的时候"设置"按钮会移动到“tabs”栏上面（“刷新”按钮左边），先看看这个模式是否通过你们的评审。

**Pull request merged**
