### PR TITLE
feat: 系统主题功能

### PR DESCRIPTION
**Pull request by xingyuv**
### `General`

> ✏️ Mark the necessary items without changing the structure of the PR template.

- [ ] Pull request template structure not broken

### `Type`

> ℹ️ What types of changes does your code introduce?

> 👉 _Put an `x` in the boxes that apply_

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### `Checklist`

> ℹ️ Check all checkboxes - this will indicate that you have done everything in accordance with the rules in [CONTRIBUTING](contributing.md).

> 👉 _Put an `x` in the boxes that apply._

- [ ] My code follows the style guidelines of this project
- [ ] Is the code format correct
- [ ] Is the git submission information standard?
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by xingyuv** [comment]
image

**Comment by xingyuv** [comment]
升级依赖的也一起提交了，应该是创建分支选择错了。。。如果不升级的话我再重新提吧

**Comment by wangjue666** [comment]
> 升级依赖的也一起提交了，应该是创建分支选择错了。。。如果不升级的话我再重新提吧

这种情况 分成两个PR进行提交就好

**Comment by wangjue666** [comment]
image

这些位置的颜色也应做出对应调整

**Comment by xingyuv** [comment]
> image
> 
> 这些位置的颜色也应做出对应调整

这些如果要调整，改动会比较大，建议是去掉 兼容原有v3方案，直接用最新的主题方案

**Comment by zwtvip** [comment]
我也推荐用最新的，之前的兼容的样式代码去掉

**Comment by wangjue666** [comment]
可以搞

> 这些如果要调整，改动会比较大，建议是去掉 兼容原有v3方案，直接用最新的主题方案

**Pull request closed without merging**
