### PR TITLE
perf(ConfigProvider): 配置antdv主题色, 使其与modifyVars配置一致

### PR DESCRIPTION
**Pull request by WitMiao**
### `General`

> ✏️ Mark the necessary items without changing the structure of the PR template.

- [x] Pull request template structure not broken

### `Type`

> ℹ️ What types of changes does your code introduce?

> 👉 _Put an `x` in the boxes that apply_

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### `Checklist`

> ℹ️ Check all checkboxes - this will indicate that you have done everything in accordance with the rules in [CONTRIBUTING](contributing.md).

> 👉 _Put an `x` in the boxes that apply._

- [x] My code follows the style guidelines of this project
- [x] Is the code format correct
- [x] Is the git submission information standard?
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by zwtvip** [comment]
你这个方法updateCustomColor得在initAppConfig.ts 里面初始化调用一下，不然切换主题会有一些问题，例如表格斑马样式

**Comment by zwtvip** [comment]
> > 你这个方法updateCustomColor得在initAppConfig.ts 里面初始化调用一下，不然切换主题会有一些问题，例如表格斑马样式
> 
> 我在updateDarkTheme里调用updateCustomColor了，算是更新深色主题的子功能，initAppConfig有调用updateDarkTheme
你这里改下颜色：{
    name: '--app-content-background-color',
    light: '#fafafa',
    dark: '#1e1e1e',
  },
你全局搜素这个 加个important
 &-row__striped {
      td {
        background-color: @app-content-background !important;
      }
    }

**Comment by WitMiao** [comment]
zhang
你这个方法updateCustomColor得在initAppConfig.ts 里面初始化调用一下，不然切换主题会有一些问题，例如表格斑马样式 我在updateDarkTheme里调用updateCustomColor了，算是更新深色主题的子功能，initAppConfig有调用updateDarkTheme 你这里改下颜色：{ name: '--app-content-background-color', light: '#fafafa', dark: '#1e1e1e', }, 你全局搜素这个 加个important &-row__striped { td { background-color: @app-content-background !important; } }
ok, 这个深色斑马色是太类似了😂，分不清，我换下

[苗大（Wit〆苗大） - Chat @ Spike](https://spikenow.com/r/a/?ref=spike-organic-signature&_ts=2bdex0)	[2bdex0]

On October 31, 2023 at 10:34 GMT, zhang ***@***.***> wrote:

你这个方法updateCustomColor得在initAppConfig.ts 里面初始化调用一下，不然切换主题会有一些问题，例如表格斑马样式

我在updateDarkTheme里调用updateCustomColor了，算是更新深色主题的子功能，initAppConfig有调用updateDarkTheme
你这里改下颜色：{
name: '--app-content-background-color',
light: '#fafafa',
dark: '#1e1e1e',
},
你全局搜素这个 加个important
&-row__striped {
td {
background-color: @app-content-background !important;
}
}

**Comment by WitMiao** [comment]
> > > 你这个方法updateCustomColor得在initAppConfig.ts 里面初始化调用一下，不然切换主题会有一些问题，例如表格斑马样式
> > 
> > 
> > 我在updateDarkTheme里调用updateCustomColor了，算是更新深色主题的子功能，initAppConfig有调用updateDarkTheme
> > 你这里改下颜色：{
> > name: '--app-content-background-color',
> > light: '#fafafa',
> > dark: '#1e1e1e',
> > },
> > 你全局搜素这个 加个important
> > &-row__striped {
> > td {
> > background-color: @app-content-background !important;
> > }
> > }

已修正

**Pull request merged**
