### PR TITLE
Update package.json

### PR DESCRIPTION
**Pull request by qq34347476**
dayjs 替换 moment

### `General`

> ✏️ Mark the necessary items without changing the structure of the PR template.

- [ ] Pull request template structure not broken

### `Type`

> ℹ️ What types of changes does your code introduce?

> 👉 _Put an `x` in the boxes that apply_

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### `Checklist`

> ℹ️ Check all checkboxes - this will indicate that you have done everything in accordance with the rules in [CONTRIBUTING](contributing.md).

> 👉 _Put an `x` in the boxes that apply._

- [ ] My code follows the style guidelines of this project
- [ ] Is the code format correct
- [ ] Is the git submission information standard?
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by mynetfan** [comment]
没有使用dayjs的原因是当前版本的antdv使用的是moment

**Comment by qq34347476** [comment]
我刚提交的是如何替换dayjs，包括antv中的方法，



发自我的iPhone


------------------ Original ------------------
From: Netfan ***@***.***&gt;
Date: Thu,Sep 16,2021 1:30 PM
To: anncwb/vue-vben-admin ***@***.***&gt;
Cc: Jiang ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [anncwb/vue-vben-admin] Update package.json (#1210)





 
没有使用dayjs的原因是当前版本的antdv使用的是moment

**Comment by anncwb** [comment]
暂时不会换，因为antv用到了，在加dayjs反倒多余了

**Comment by tzwhyqq** [comment]
ant3.0版本已经替换成dayjs 坐等 ant3.0正式发布

**Pull request closed without merging**
