### PR TITLE
fix: form 表单不支持field.xxx.xx格式的defaultValue配置

### PR DESCRIPTION
**Pull request by leizhiyou**
## Description

Form 表单useVbenForm 无法设置表单字段 field.xx.xx 的defaultValue的默认值配置

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] Please, don't make changes to `pnpm-lock.yaml` unless you introduce a new test example.

## Checklist

> ℹ️ Check all checkboxes - this will indicate that you have done everything in accordance with the rules in [CONTRIBUTING](contributing.md).

- [ ] If you introduce new functionality, document it. You can run documentation with `pnpm run docs:dev` command.
- [ ] Run the tests with `pnpm test`.
- [ ] Changes in changelog are generated from PR name. Please, make sure that it explains your changes in an understandable manner. Please, prefix changeset messages with `feat:`, `fix:`, `perf:`, `docs:`, or `chore:`.
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

## Release Notes

- **New Features**
	- Introduced a new input field in the form for capturing nested property paths.
	- Added the `set` function from lodash to enhance utility functions for manipulating object properties.

- **Bug Fixes**
	- Improved handling of initial values in forms, allowing for more flexible assignments to nested properties.

- **Chores**
	- Updated package configurations to include new lodash dependencies for enhanced type support.

### CODE REVIEW

**Review by anncwb — APPROVED** [review]

**Comment by vince292007** [comment]
ci没通过

**Comment by leizhiyou** [comment]
> ci没通过

是因为依赖版本不是最新的，我这边修改一下版本再重新提交么？

**Comment by leizhiyou** [comment]
> ci没通过

哦，我看到那里没通过了，我处理一下再重新提交

**Review by anncwb — APPROVED** [review]

**Comment by ChenWeihua123** [comment]
这个功能 在 5.5.0 好像并没有发布上去 use-form-context.ts 没看到修改后的代码

**Pull request merged**
