### PR TITLE
fix: repair login about redirect query

### PR DESCRIPTION
**Pull request by xachary**
### `General`

> 根据反馈 https://github.com/vbenjs/vue-vben-admin/issues/3588 重现问题，根源：
> src\store\modules\user.ts 重复并提前执行了 permissionStore.setDynamicAddedRoute(true)，导致 src\router\guard\permissionGuard.ts 无法通过到逻辑最后（不知道理解的对不对，测试通过部分场景）。
> 另外，目前登出均为 logout(true)，理应区分”主动“和”被动“两种场景，”主动“不带 redirect 回到登陆页，”被动“带。

- [x] Pull request template structure not broken

### `Type`

> ℹ️ What types of changes does your code introduce?

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### `Checklist`

> ℹ️ Check all checkboxes - this will indicate that you have done everything in accordance with the rules in [CONTRIBUTING](contributing.md).

- [x] My code follows the style guidelines of this project
- [x] Is the code format correct
- [x] Is the git submission information standard?
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by dapeng0201** [comment]
在后台路由模式下  登录操作会执行两次buildRoutesAction()
```ts
// Permission mode
permissionMode: PermissionModeEnum.BACK,
```
image
image

**Comment by xachary** [comment]
@dapeng0201 有道理，试试最新这个

**Comment by dapeng0201** [comment]
> @dapeng0201 有道理，试试最新这个
测试正常(后台路由)  被动退出登录也能正常redirect
但是redirect如果是一个不存在的路由(用户输入)  界面会卡死且没有报错信息  这个有办法判断直接跳到首页吗
image

**Comment by xachary** [comment]
@dapeng0201 666，again

**Comment by dapeng0201** [comment]
> @dapeng0201 666，again

ok了  在前端/后端路由都正常  包括
- 被动退出登录带redirect  重新登录跳转到对应页面
- 主动退出登录不带redirect   重新登录跳转到首页
- redirect为不存在的路径   重新登录跳转到首页

**Pull request merged**
