### PR TITLE
fix(LockModal): Cannot unlock

### PR DESCRIPTION
**Pull request by jiaowoxiaobala**
### `General`

> ✏️ Mark the necessary items without changing the structure of the PR template.

- [ ] Pull request template structure not broken

### `Type`

> ℹ️ What types of changes does your code introduce?

> 👉 _Put an `x` in the boxes that apply_

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### `Checklist`

> ℹ️ Check all checkboxes - this will indicate that you have done everything in accordance with the rules in [CONTRIBUTING](contributing.md).

> 👉 _Put an `x` in the boxes that apply._

- [x] My code follows the style guidelines of this project
- [x] Is the code format correct
- [x] Is the git submission information standard?
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by wangjue666** [comment]
@jiaowoxiaobala  可以解锁屏幕呀，只是重构了下这块吗？

**Comment by likui628** [comment]
> @jiaowoxiaobala 可以解锁屏幕呀，只是重构了下这块吗？

解锁有2种方式，登录密码和锁屏密码。目前是锁屏密码解锁出问题了

**Comment by jiaowoxiaobala** [comment]
> @jiaowoxiaobala 可以解锁屏幕呀，只是重构了下这块吗？

@wangjue666 锁屏密码解锁bug

**Comment by wangjue666** [comment]
@jiaowoxiaobala  ok

**Pull request merged**
