### PR TITLE
fix(tabs): 修复标签页快捷菜单缩小问题

### PR DESCRIPTION
**Pull request by freespace8**
### `General`

> ✏️ Mark the necessary items without changing the structure of the PR template.

- [ ] Pull request template structure not broken

### `Type`

> ℹ️ What types of changes does your code introduce?
image

> 👉 _Put an `x` in the boxes that apply_

- [ x ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### `Checklist`

> ℹ️ Check all checkboxes - this will indicate that you have done everything in accordance with the rules in [CONTRIBUTING](contributing.md).

> 👉 _Put an `x` in the boxes that apply._

- [ ] My code follows the style guidelines of this project
- [ ] Is the code format correct
- [ ] Is the git submission information standard?
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by likui628** [comment]
这个bug有没有办法复现

**Comment by freespace8** [comment]
> 这个bug有没有办法复现

在我这里基本上都是有问题的，有概率是好的，测试过直接把 css 的 left 去掉，会自动加回来，感觉是 antdv 组件一直在计算

**Comment by likui628** [comment]
窗口拉窄一点，没解决问题
image

**Comment by freespace8** [comment]
> 窗口拉窄一点，没解决问题
> image
> 

应该是 antdv 的 bug

**Comment by likui628** [comment]
那就先关了哦

**Pull request closed without merging**
