### PR TITLE
style: adaptation issues in dark mode

### PR DESCRIPTION
**Pull request by pingsanddoss**
## Description

黑暗模式下菜单等主题的适配

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] Please, don't make changes to `pnpm-lock.yaml` unless you introduce a new test example.

## Checklist

> ℹ️ Check all checkboxes - this will indicate that you have done everything in accordance with the rules in [CONTRIBUTING](contributing.md).

- [x] If you introduce new functionality, document it. You can run documentation with `pnpm run docs:dev` command.
- [x] Run the tests with `pnpm test`.
- [x] Changes in changelog are generated from PR name. Please, make sure that it explains your changes in an understandable manner. Please, prefix changeset messages with `feat:`, `fix:`, `perf:`, `docs:`, or `chore:`.
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

## Summary by CodeRabbit

- **New Features**
	- Enhanced menu functionality with improved responsiveness and visual appeal.
	- Updated styling for active and hover states in menu and tab components.

- **Bug Fixes**
	- Adjusted state management for menu items to ensure proper initialization and updates.

- **Style**
	- Refined hover effects, transitions, and color schemes for menu items and tabs for better visual consistency across themes.

### CODE REVIEW

**Comment by vince292007** [comment]
这个之前改成accent的原因是，有些皮肤是浅色色，这个改成主色会有点问题

**Comment by pingsanddoss** [comment]
我感觉全是黑白的好像不是很好看，逻辑上主题色是用户自己选择的，在黑暗模式下最好也展示出主题色，希望作者可以考虑一下

**Comment by vince292007** [comment]
后面看看，考虑价格配置菜单色的功能吧，跟主题色分离开

**Comment by pingsanddoss** [comment]
那这个pr接受吗，我觉得可以试一下，后面有其他方案可以再改^_^

**Review by vince292007 — DISMISSED** [review]

**Comment by anncwb** [comment]
ci没有通过

**Comment by pingsanddoss** [comment]
再试试

**Comment by anncwb** [comment]
这个先暂定下，目前有写皮肤下是有问题。后面整体优化配色的时候在看下

**Comment by pingsanddoss** [comment]
好的谢谢作者

**Pull request closed without merging**
