### PR TITLE
chore: up vite5

### PR DESCRIPTION
**Pull request by xingyuv**
### `General`

> ✏️ Mark the necessary items without changing the structure of the PR template.

- [ ] Pull request template structure not broken

### `Type`

> ℹ️ What types of changes does your code introduce?

> 👉 _Put an `x` in the boxes that apply_

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### `Checklist`

> ℹ️ Check all checkboxes - this will indicate that you have done everything in accordance with the rules in [CONTRIBUTING](contributing.md).

> 👉 _Put an `x` in the boxes that apply._

- [ ] My code follows the style guidelines of this project
- [ ] Is the code format correct
- [ ] Is the git submission information standard?
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by xingyuv** [comment]
https://github.com/vbenjs/vue-vben-admin/issues/3425

**Comment by wangjue666** [comment]
@xingyuv  很棒~ 除了部分警告外，功能不受影响

**Comment by xingyuv** [comment]
> @xingyuv 很棒~ 除了部分警告外，功能不受影响

vite:html 这个就是要vben那个依赖去改了

cjs 这一块目前不太好找是哪里的问题，现在不影响使用和打包了

**Comment by wangjue666** [comment]
好 那就先合并！

**Review by wangjue666 — APPROVED** [review]

**Comment by xachary** [comment]
@wangjue666 最新版本 type:check 能通过？
https://github.com/vbenjs/vue-vben-admin/pull/3514

**Comment by DesignHhuang** [comment]
image
@xingyuv @wangjue666  我不太明白，这边为啥要把所有的js 改成 cjs。cjs已经弃用了，为什么不保持js 或者 mjs？

**Pull request merged**
