### PR TITLE
perf: 解决提交代码时stylelint格式化less和scss的媒体查询为不支持的语法(Media Queries Level 4)

### PR DESCRIPTION
**Pull request by lessroc**
### `General`

> ✏️ Mark the necessary items without changing the structure of the PR template.

- [x] Pull request template structure not broken

### `Type`

> ℹ️ What types of changes does your code introduce?

> 👉 _Put an `x` in the boxes that apply_

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### `Checklist`

> ℹ️ Check all checkboxes - this will indicate that you have done everything in accordance with the rules in [CONTRIBUTING](contributing.md).

> 👉 _Put an `x` in the boxes that apply._

- [x] My code follows the style guidelines of this project
- [x] Is the code format correct
- [x] Is the git submission information standard?
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by lessroc** [comment]
less does not support media queries level 4

[Less](https://www.npmjs.com/package/less) 有些许时间没有更新了，目前最新版本[4.1.3](https://www.npmjs.com/package/less?activeTab=versions)暂不支持[媒体查询版本_4_中的语法改进](https://developer.mozilla.org/zh-CN/docs/Web/CSS/CSS_media_queries/Using_media_queries#%E7%89%88%E6%9C%AC_4_%E4%B8%AD%E7%9A%84%E8%AF%AD%E6%B3%95%E6%94%B9%E8%BF%9B)

具体表现见：[less/issues](https://github.com/less/less.js/issues/3735)

产生这个错误的原因是使用的[stylelint](https://github.com/stylelint/stylelint)更新到了比较新的版本[15.10.1](https://github.com/stylelint/stylelint/releases/tag/15.10.1)，这个版本包含了[media-feature-range-notation](https://github.com/stylelint/stylelint/pull/6497)规则

允许:
```css
@media screen and (500px <= width <= 1200px) {
  .bar {
    display: block;
  }
}
```

不允许:
```css
@media screen and (min-width: 500px) and (max-width: 1200px) {
  .bar {
    display: block;
  }
}
```

为避免在提交代码时不被[stylelint](https://github.com/stylelint/stylelint)意外的格式媒体查询为[版本_4_中的语法](https://developer.mozilla.org/zh-CN/docs/Web/CSS/CSS_media_queries/Using_media_queries#%E7%89%88%E6%9C%AC_4_%E4%B8%AD%E7%9A%84%E8%AF%AD%E6%B3%95%E6%94%B9%E8%BF%9B)

在[internal/stylelint-config/src/index.ts](https://github.com/vbenjs/vue-vben-admin/blob/16b4b6d57c9781773c7454a66f7e5518880971b9/internal/stylelint-config/src/index.ts#L24C11-L24C11)配置中添加一条规则:

```ts
rules: {
  'media-feature-range-notation': null,
  // ...
}
```

**Comment by Tairy** [comment]
改了没有效果是咋回事呢

**Comment by lessroc** [comment]
使用的相关包版本多少呀，有没有拉最新的分支下来合并呢

**Comment by susanliy** [comment]
拉去了最新的代码  这个问题还是存在的 
image

**Pull request merged**
