### PR TITLE
fix(deepMerge): 修复递归合并操作, 合并数组未去重的bug

### PR DESCRIPTION
**Pull request by WitMiao**
### `General`
#2660 #2663 这些issues提出的问题就是这个bug导致的
> ✏️ Mark the necessary items without changing the structure of the PR template.

- [x] Pull request template structure not broken

### `Type`

> ℹ️ What types of changes does your code introduce?

> 👉 _Put an `x` in the boxes that apply_

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### `Checklist`

> ℹ️ Check all checkboxes - this will indicate that you have done everything in accordance with the rules in [CONTRIBUTING](contributing.md).

> 👉 _Put an `x` in the boxes that apply._

- [x] My code follows the style guidelines of this project
- [x] Is the code format correct
- [x] Is the git submission information standard?
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by VENI-VIDIVICI** [comment]
@WitMiao 
这个没解决吧？还是能复现

**Comment by wangyuzhu** [comment]
BUG还存在

**Comment by guoao0809** [comment]
BUG还存在

**Comment by EricHe56** [comment]
并没有解决问题，因为const treeData = await getDeptList(); 中获取到的新树大部分与旧树重合，只有添加了子对象的那个元素会有差异，也就会被保留。同时，原有的那个元素也会保留，因为是唯一。这里应该给一个参数允许替换，而不是合并。

**Comment by guoao0809** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by smilecode11** [comment]
2023年05月12日01:27:56 此时还未解决, 我是用的是基础版

**Comment by guoao0809** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by gnyuan** [comment]
Bug依旧存在。

**Comment by guoao0809** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Pull request merged**
