### PR TITLE
feat: add reize components & demo

### PR DESCRIPTION
**Pull request by ArthurDarkstone**
## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] Please, don't make changes to `pnpm-lock.yaml` unless you introduce a new test example.

## Checklist

> ℹ️ Check all checkboxes - this will indicate that you have done everything in accordance with the rules in [CONTRIBUTING](contributing.md).

- [ ] If you introduce new functionality, document it. You can run documentation with `pnpm run docs:dev` command.
- [ ] Run the tests with `pnpm test`.
- [ ] Changes in changelog are generated from PR name. Please, make sure that it explains your changes in an understandable manner. Please, prefix changeset messages with `feat:`, `fix:`, `perf:`, `docs:`, or `chore:`.
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

## Release Notes

- **New Features**
  - Introduced a draggable and resizable UI component (`VResize`) for enhanced user interaction.
  - Added a new demo route for the resizing feature, accessible at `/demos/resize/basic`.

- **Localization**
  - Enhanced localization with a new entry for the resize feature in Chinese.

- **Bug Fixes**
  - Updated configuration settings for better compatibility and functionality.

These updates improve the overall user experience by adding new interactive elements and enhancing localization support.

### CODE REVIEW

**Comment by ArthurDarkstone** [comment]
still, need refactor.

**Comment by vince292007** [comment]
这个是组件，应该可以放到examples内，而不是demo文件夹

**Comment by ArthurDarkstone** [comment]
resize 组件超过1000行了，优化一下试试

**Comment by vince292007** [comment]
css比较少，感觉可以改成tailwindcss，减少pacakges对scss的依赖

**Comment by ArthurDarkstone** [comment]
> css比较少，感觉可以改成tailwindcss，减少pacakges对scss的依赖

可以的，再封装一个hook还能更精简些

**Comment by ArthurDarkstone** [comment]
https://github.com/user-attachments/assets/cd43b2a7-1c9b-4226-a97d-d9c21ddb1f1e

**Comment by ArthurDarkstone** [comment]
> css比较少，感觉可以改成tailwindcss，减少pacakges对scss的依赖

当时写错了lang的类型，其实没有用到scss，只是css。用tailwind 是否激活状态比较难处理，还是先不改成tailwind了

**Review by vince292007 — APPROVED** [review]

**Pull request merged**
