### PR TITLE
chore: update vite v5

### PR DESCRIPTION
**Pull request by xingyuv**
### `General`

> ✏️ Mark the necessary items without changing the structure of the PR template.

- [ ] Pull request template structure not broken

### `Type`

> ℹ️ What types of changes does your code introduce?

> 👉 _Put an `x` in the boxes that apply_

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### `Checklist`

> ℹ️ Check all checkboxes - this will indicate that you have done everything in accordance with the rules in [CONTRIBUTING](contributing.md).

> 👉 _Put an `x` in the boxes that apply._

- [ ] My code follows the style guidelines of this project
- [ ] Is the code format correct
- [ ] Is the git submission information standard?
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by wangjue666** [comment]
看下ci信息 有类型错误

**Comment by wangjue666** [comment]
@xingyuv  哥这个功能能否拆分提交，一个PR聚焦解决一个问题，太多改动看不过来也不好测试

**Comment by xingyuv** [comment]
> @xingyuv 哥这个功能能否拆分提交，一个PR聚焦解决一个问题，太多改动看不过来也不好测试

vite-plugin-html 这个是因为升级vite5会报有一些过期的警告，而vben这个已经很久没更新版本了也不确定后续是否会继续更新，只能挪进来，升级了一些依赖和修复过期的方法

**Comment by wangjue666** [comment]
> vite-plugin-html 这个是因为升级vite5会报有一些过期的警告，而vben这个已经很久没更新版本了也不确定后续是否会继续更新，只能挪进来，升级了一些依赖和修复过期的方法

这样吧， 一个commit提交一个PR 测试没问题的话再提交下个PR，这样出问题好及时回滚或调整

image

**Pull request closed without merging**
