### PR TITLE
fix: 修复Input组件field为search时，使用setFieldsValue，value校验为Funtion异常  #3966

### PR DESCRIPTION
**Pull request by clddup**
这里如果是常见组件, 不应该使用`get(value, key)` 获取,  否则会获取到该值的一些js内置方法

### `General`

> ✏️ Mark the necessary items without changing the structure of the PR template.

- [x] Pull request template structure not broken

### `Type`

> ℹ️ What types of changes does your code introduce?

> 👉 _Put an `x` in the boxes that apply_

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### `Checklist`

> ℹ️ Check all checkboxes - this will indicate that you have done everything in accordance with the rules in [CONTRIBUTING](contributing.md).

> 👉 _Put an `x` in the boxes that apply._

- [x] My code follows the style guidelines of this project
- [x] Is the code format correct
- [x] Is the git submission information standard?
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by wangjue666** [comment]
@clddup  提供个复现demo吧 我看看

**Comment by clddup** [comment]
> @clddup 提供个复现demo吧 我看看

ok 那我现在基于 https://github.com/vbenjs/vue-vben-admin/issues/3966 做个复现demo

**Comment by clddup** [comment]
> @clddup 提供个复现demo吧 我看看

我先在 https://github.com/clddup/vue-vben-admin/tree/vue-vben-admin-issues-3966 复现了此问题

点击 issues-3966 按钮即可复现

image

image

我调用方法为

image

**Comment by clddup** [comment]
> Hello @clddup,
> 
> I believe you need to add a condition to the `search` field only to apply this bug fix.
> 
> Removing the code below will cause another bug, as a form field value can be an object or array:
> 
> ```js
> const constructValue = get(value, key);
> const fieldValue = constructValue || value;
> ```

ok 我明白了

**Comment by clddup** [comment]
> Hello @clddup,
> 
> I believe you need to add a condition to the `search` field only to apply this bug fix.
> 
> Removing the code below will cause another bug, as a form field value can be an object or array:
> 
> ```js
> const constructValue = get(value, key);
> const fieldValue = constructValue || value;
> ```

它不仅限于 search, 如果我的value值为字符串, 所有字符串的内置原型上的方法都将导致此问题, 比如 includes, split 这些方法, 如果是别的类型, 其value的内置原型上的方法也同样会导致此问题, 我任务在没有想清楚解决这种问题之前, 不应该采用这种方法
```js
constructValue = get(value, key);
const fieldValue = constructValue || value;
```

**Comment by clddup** [comment]
我将删除此次提交

**Comment by clddup** [comment]
> @clddup 为啥呀
> 
> > 我将删除此次提交

因为前几天刚接触这个框架, 对代码熟悉度较浅, 此次修改考虑不够完善, 可以由你们来修改

**Comment by clddup** [comment]
> @clddup
> 
> You can submit another pull request where you adjust the changes so that they only apply to the "search" input field, ensuring that the fix or changes won't affect the current behavior. I think that will be the best option for now.
> 
> Translation: 您可以提交另一个拉取请求，在其中调整更改，以便它们仅适用于“搜索”输入字段，确保修复或更改不会影响当前行为。我认为这将是目前最好的选择。

感谢你的建议, 鉴于目前对代码的熟悉度, 我将放弃此次修改

**Pull request closed without merging**
